name: flutter_application_1
description: "Application de gestion immobilière et maintenance."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Icônes et affichage
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1

  # Base de données et stockage
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Gestion de l'état et des fichiers
  provider: ^6.1.2
  path: ^1.9.1
  image_picker: ^1.1.2

  # Calendrier et internationalisation
  table_calendar: ^3.0.9
  intl: ^0.19.0

  # Utilitaires
  url_launcher: ^6.2.5
  pdf: ^3.10.8
  printing: ^5.12.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
